Repository JeanCHilger/reveal-plus, pull requests merged in 2020-05, with the labels that each got.

#20 Complete code spliting
  doAll_Baseline_4gram
  main
  preprocess
  training
Labels: refactor

#24 Update README.md
  README.md
Labels: documentation

#27 Cord 19 qrels and judgement files
  data-extraction-scripts/doc_uid_mapping.py
  data-extraction-scripts/extract_judgements.py
  data-extraction-scripts/extract_queries.py
  judgement/cord-19.topic.stemming.txt
  judgement/qrels.cord-19.list
Labels: enhancement
